openapi: 3.0.3
info:
  title: Notebook API Definition
  version: 0.0.0
paths:
  /notebook:
    get:
      operationId: getAListOfAllNotebooks
      summary: Get a list of all notebooks.
      responses:
        "200":
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        url:
                          type: string
                      required:
                        - title
                        - url
                required:
                  - data
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description:
            Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "403":
          description:
            The server understood the request, but refuses to authorize it.
            Ensure the client has appropriate permissions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
    post:
      operationId: createANewNotebook
      summary: Create a new notebook.
      responses:
        "201":
          description: The request was successful, and a new resource was created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notebook"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description:
            Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "403":
          description:
            The server understood the request, but refuses to authorize it.
            Ensure the client has appropriate permissions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
      requestBody:
        required: true
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
  /notebook/{id}:
    get:
      operationId: getTheLatestVersionOfANotebook
      summary: Get the latest version of a notebook
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notebook"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description:
            Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "403":
          description:
            The server understood the request, but refuses to authorize it.
            Ensure the client has appropriate permissions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
    put:
      operationId: sendAChangeMessageForASpecificNotebook
      summary: Send a change message for a specific notebook
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "202":
          description:
            The request has been accepted for processing, but the processing
            has not been completed. The request might be processed later.
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description:
            Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "403":
          description:
            The server understood the request, but refuses to authorize it.
            Ensure the client has appropriate permissions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerErrror"

      requestBody:
        required: true
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                targetId:
                  type: string
                content:
                  type: object
              required:
                - type
                - targetId
                - content
    delete:
      operationId: sendsRequestToDeleteNotebook
      summary: Sends request to delete notebook.
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "202":
          description:
            The request has been accepted for processing, but the processing
            has not been completed. The request might be processed later.

        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description:
            Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "403":
          description:
            The server understood the request, but refuses to authorize it.
            Ensure the client has appropriate permissions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
  /notebook/{id}/versions:
    get:
      operationId: getAllVersionsOfANotebook
      summary: Get all versions of a notebook.
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        createdAt:
                          type: string
                        url:
                          type: string
                      required:
                        - createdAt
                        - url
                required:
                  - data
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description:
            Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "403":
          description:
            The server understood the request, but refuses to authorize it.
            Ensure the client has appropriate permissions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
  /block/{id}:
    get:
      operationId: getTheLatestVersionOfABlock
      summary: Get the latest version of a block.
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      versionId:
                        type: string
                      type:
                        type: string
                      title:
                        type: string
                      content:
                        type: object
                    required:
                      - id
                      - versionId
                      - type
                      - title
                      - content
                required:
                  - data
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description:
            Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "403":
          description:
            The server understood the request, but refuses to authorize it.
            Ensure the client has appropriate permissions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
  /block/{id}/version:
    get:
      operationId: getAllTheVersionOfASpecificBlock
      summary: Get all the version of a specific block.
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      createdAt:
                        type: string
                      url:
                        type: string
                    required:
                      - createdAt
                      - url
                required:
                  - data
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description:
            Authentication is required to access the requested resource. The
            client must include the appropriate credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "403":
          description:
            The server understood the request, but refuses to authorize it.
            Ensure the client has appropriate permissions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
components:
  responses:
    BadRequest:
      description:
        The server could not understand the request due to invalid syntax.
        The client should modify the request and try again.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                  required:
                    - message
            required:
              - message
    InternalServerErrror:
      description:
        The server encountered an unexpected condition that prevented it
        from fulfilling the request. Report the issue to the support team if it
        persists.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    NotFound:
      description:
        The server cannot find the requested resource. The endpoint may be
        invalid or the resource may no longer exist.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    Conflict:
      description: The request could not be completed due to a conflict with the
        current state of the resource. Resolve the conflict and try again.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
  schemas:
    notebook:
      type: object
      properties:
        metadata:
          type: object
          properties:
            title:
              type: string
            ownerId:
              type: string
            createdAt:
              type: string
          required:
            - title
            - ownerId
            - createdAt
        versionId:
          type: string
        blocks:
          type: object
          properties:
            type:
              type: string
            url:
              type: string
          required:
            - type
            - url
      required:
        - metadata
        - versionId
        - blocks
      description: ""
